### ISSUE TITLE
PackageName details are not displayed. more than 10 lines away

### ISSUE THREAD

**Issue by nakacya** [ishiDACo/vulsrepo#122]
It's difficult to explain, so I'm using Japanese.
Simply put, the link to the PackageName that is "more than 10 lines away" cannot be displayed.

**Comment by ishiDACo** [comment]
確かに、クリックしても反応しないですね。

I'm sure. It doesn't respond to a click.

![image](https://user-images.githubusercontent.com/2542762/97012805-393b0380-1583-11eb-982c-6d68918a4793.png)

**Comment by nakacya** [comment]
余り問題になる内容ではありませんが気が向いた時にでも改修されると嬉しいです

I don't think it's too much of a problem, but it would be nice to have it fixed up whenever you're ready.

**Comment by ishiDACo** [comment]
I fix it!
