### ISSUE TITLE
When the same data is loaded twice, the color of the heatmap is strongly colored.

### ISSUE THREAD

**Issue by nakacya** [ishiDACo/vulsrepo#125]
1. Select and display data.
2. Display the same data choices again.
3. The color of the heat map is emphasized.

It's easy to see because it's highlighted with no problems.

**Comment by ishiDACo** [comment]
I have confirmed that I can reproduce it too.

**Comment by nakacya** [comment]
In fact, it might be easier to see this kind of tone

**Comment by ishiDACo** [comment]
I fixed it!

**Comment by ishiDACo** [comment]
Oops, Not fixed yet...

**Comment by ishiDACo** [comment]
Misunderstanding. I fixed it.

degrade.

https://github.com/ishiDACo/vulsrepo/commit/7638c3462532474f357c0a0397e94f89384100e0
