### ISSUE TITLE
Invalid `warnings` and `errors` types

### ISSUE THREAD

**Issue by Jiab77** [ishiDACo/vulsrepo#165]
I have several reports that can be viewed with the interface so I took the time to dig a little further and I've found the cause.

In the working reports, both `warnings` and `errors` object properties are in `array` type but on the non-working reports, both are in `null` type.

__Working reports:__

```json
  "errors": [],
  "warnings": [],
```

__Non-Working reports:__

```json
  "errors": null,
  "warnings": null,
```

So the current code will not be able to manage the `null` type:

```js
    if (data.warnings.length > 0) {
        servername = "[Warn] " + servername;
    }
```

As seen here:

![image](https://user-images.githubusercontent.com/9881407/99075277-7fe7b080-25b9-11eb-9d14-de3a809bf26a.png)

and here:

![image](https://user-images.githubusercontent.com/9881407/99075342-9aba2500-25b9-11eb-99a9-fab76ceb59e4.png)

__Proposed Patch:__

```js
    if (data.warnings !== null && data.warnings.length > 0) {
        servername = "[Warn] " + servername;
    }
```

I have not tested it but it should work that way. If that work, then it might be done also for `data.errors` I guess 😅

**Comment by Jiab77** [comment]
Here is a temporary workaround that will patch `JSON` reports and make them viewable in the web interface :)

```bash
find ${REPORT_FOLDER} -type f -iname "*.json" \
-exec echo "Patching file {} ..." \; \
-exec cp -v "{}" "{}.bak" \; \
-exec sed -e 's/"errors"\: null/"errors"\: \[\]/' -i "{}" \; \
-exec sed -e 's/"warnings"\: null/"warnings"\: \[\]/' -i "{}" \;
```

> Just replace `${REPORT_FOLDER}` by the real location of the `results` folder.

**Comment by ishiDACo** [comment]
Thanks for the report.
I didn't realize there was a null pattern.
I'll fix it so that it doesn't cause an error with null.

**Comment by ishiDACo** [comment]
I fixed it!

**Comment by Jiab77** [comment]
> Thanks for the report.
> I didn't realize there was a null pattern.
> I'll fix it so that it doesn't cause an error with null.

You're welcome! I'm glad I could be helpful :)

**Comment by Jiab77** [comment]
> I fixed it!

Nice! Thank you so much! Even if my report patch script was working well, patching them all was not really the best solution 😅
