### ISSUE TITLE
Authentication loop on Chromium and Firefox

### ISSUE THREAD

**Issue by Jiab77** [ishiDACo/vulsrepo#169]
### Description

Hello @ishiDACo, I'm trying to enable the authentication but it creates an authentication loop when using Chromium or Firefox but not when using the terminal browser `w3m`. Before opening this issue I've tried to debug this authentication loop and I think it's a timeout issue from what I could see with `strace`.

### Debug steps

1. Start the vulsrepo-server
2. Get the PID with `ps aux | grep vulsrepo-server`
3. Run `strace -p PID` as root
4. Open the URL with Chrome, Chromium or Firefox
5. Hit F12 to open the dev console then go to the network tab
5. Check the "preserve log" checkbox

### Observed

* Before entering password:

![image](https://user-images.githubusercontent.com/9881407/99526009-ee05ec00-299a-11eb-8662-723cd7a254ae.png)
![image](https://user-images.githubusercontent.com/9881407/99526110-1857a980-299b-11eb-8161-e0a34c41f6f5.png)

* After entering password (first time):

![image](https://user-images.githubusercontent.com/9881407/99526337-68367080-299b-11eb-9e6c-4724445fd394.png)
![image](https://user-images.githubusercontent.com/9881407/99526533-ab90df00-299b-11eb-8fdd-593d107c9a10.png)
![image](https://user-images.githubusercontent.com/9881407/99527441-1989d600-299d-11eb-867b-52f5f6b7eff2.png)

* After entering password (second time):

![image](https://user-images.githubusercontent.com/9881407/99527620-61106200-299d-11eb-9729-b723ad4b9e9d.png)
![image](https://user-images.githubusercontent.com/9881407/99527689-800ef400-299d-11eb-8ae4-6d2ab1a3a949.png)
![image](https://user-images.githubusercontent.com/9881407/99527731-92892d80-299d-11eb-8639-4ae2fe7c49b1.png)

* After entering password (third time):

![image](https://user-images.githubusercontent.com/9881407/99527872-c2383580-299d-11eb-94f8-eee06cab66d7.png)
![image](https://user-images.githubusercontent.com/9881407/99528036-f9a6e200-299d-11eb-84d1-9abfaa392b73.png)

* After entering password (6 times):

![image](https://user-images.githubusercontent.com/9881407/99528378-7fc32880-299e-11eb-91eb-67a08ec2c8e1.png)
![image](https://user-images.githubusercontent.com/9881407/99528418-8f427180-299e-11eb-92e5-7682db38211d.png)

all subsequent request generates a timeout in `strace`:

```
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = -1 EAGAIN (Resource temporarily unavailable)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=3000}, NULL) = 0 (Timeout)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=3000}, NULL) = 0 (Timeout)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=3000}, NULL) = 0 (Timeout)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
read(8, "GET /plugins/pivot.js/d3_rendere"..., 4096) = 581
stat("/root/.htdigest", {st_mode=S_IFREG|0600, st_size=134, ...}) = 0
write(2, "2020/11/18 13:02:49 main.go:202:"..., 75) = 75
openat(AT_FDCWD, "/root/vulsrepo/plugins/pivot.js/d3_renderers.min.js.map", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=7020, ...}) = 0
read(7, "{\"version\":3,\"sources\":[\"/source"..., 512) = 512
lseek(7, 0, SEEK_SET)                   = 0
fstat(7, {st_mode=S_IFREG|0644, st_size=7020, ...}) = 0
write(8, "HTTP/1.1 200 OK\r\nAccept-Ranges: "..., 306) = 306
sendfile(8, 7, NULL, 7020)              = 7020
close(7)                                = 0
futex(0xc420024d10, FUTEX_WAKE, 1)      = 1
read(8, 0xc420113000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=3000}, NULL) = 0 (Timeout)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=3000}, NULL) = 0 (Timeout)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=3000}, NULL) = 0 (Timeout)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=3000}, NULL) = 0 (Timeout)
futex(0xc420024d10, FUTEX_WAKE, 1)      = 1
read(5, 0xc420014951, 1)                = -1 EAGAIN (Resource temporarily unavailable)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=3000}, NULL) = 0 (Timeout)
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
futex(0x884f90, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
epoll_wait(4, 
```

* When loading the report:

![image](https://user-images.githubusercontent.com/9881407/99529056-843c1100-299f-11eb-9182-110b4c648ad4.png)
![image](https://user-images.githubusercontent.com/9881407/99529096-928a2d00-299f-11eb-9ce7-9d91fdcf6301.png)
![image](https://user-images.githubusercontent.com/9881407/99529307-dbda7c80-299f-11eb-9448-ac3314617c6d.png)

Once entering again the password, the report got finally loaded:

![image](https://user-images.githubusercontent.com/9881407/99529515-38d63280-29a0-11eb-8523-a5592626834f.png)

### Tested

I've made the same tests with Firefox and only the amount of password requests is different (less than with Chrome or Chromium) but the issue still exist.

There is also so temporal conditions, I've tried with or without waiting each password requests, it makes not differences. You can simply chain the password entering requests, the timeout is still visible in `strace`.

When I've tried with the terminal browser `w3m`, the password request only appeared once. I guess it is due to the lack of the Javascript support.

### Config

```ini
[Server]
rootPath = "/root/vulsrepo"
resultsPath = "/root/vulsctl/install-host/results"
serverPort = "5111"
#serverIP = "127.0.0.1"
#serverSSL = "yes"
#serverCert = "cert.pem"
#serverKey = "key.pem"

[Auth]
authFilePath = "/root/.htdigest"
realm = "Vuls WebUI - Reports Viewer"
```

### Test credentials

Simply `admin`/`test`. You can also set very strong password, you will get the same result.

**Comment by Jiab77** [comment]
I forgot to mention that with our without the `HTTPS` enabled it makes no differences.

**Comment by ishiDACo** [comment]
In my environment(Chrome), repeated authentication requests were reproduced.

I'm not sure if it's the server side or the client side, but something seems to be wrong.

```sh
$ vulsrepo-server -m -r "Vuls WebUI - Reports Viewer" -c "/root/.htdigest" -u admin
Password: ****
AuthFile Path	:  /root/.htdigest
realm		:  Vuls WebUI - Reports Viewer
login user	:  admin
2020/11/19 10:20:00 main.go:100: Create Success
```

```toml
[Auth]
authFilePath = "/root/.htdigest"
realm = "Vuls WebUI - Reports Viewer"
```

**Comment by Jiab77** [comment]
@ishiDACo Thanks a lot for having tested on your side and confirmed the bug, I thought it could be something wrong on my setup.

Did you tried to connect with Firefox? What I don't understand is why there is less authentication requests than in Chrome or Chromium. It makes no sense...

I'll try to reproduce the same debugging process with Firefox and see and there is a difference somewhere, perhaps in the way to handle HTTP headers... 🤔 

I'll let you know if I find something or not.

**Comment by ishiDACo** [comment]
DigestAuth is implemented using [go-http-auth 0.4.0](https://github.com/abbot/go-http-auth).
go-http-auth 0.4.0 has Race condition in digest.go issue.
Maybe the cause is in the go-http-auth revision.

**Comment by nakacya** [comment]
I don't use go-http-auth because it has a lot of problems even when used with chrome. (It requires multiple authentications.)
If authentication is required, I think it's easier to isolate it by using nginx and vuls-report with a proxy.

It doesn't solve the problem, but it is recommended to use nginx proxy because it's easier to solve the problem.
In fact, I think it's better to remove the basic authentication logic.

**Comment by ishiDACo** [comment]
> If authentication is required, I think it's easier to isolate it by using nginx and vuls-report with a proxy.

I think so. I also recommend this method.

I'm a beginner in the Go language, so I'm not very confident in server-side modifications. 
If it's buggy, it's better to get rid of DigestAuth.

**Comment by Jiab77** [comment]
@nakacya, thanks a lot for your idea and I think it's gonna be the way that I'll follow if the latest fix from @ishiDACo does not solve the issue. @ishiDACo, I wish I could help you on the development part but I'm also a beginner in Golang... I'm just able to read it for now.

Thank you so much both for your inputs, I'm gonna run all the necessary testing by tomorrow and push results on here.

**Comment by Jiab77** [comment]
@ishiDACo, I just checked the project https://github.com/abbot/go-http-auth and by looking at the open issues and existing pull requests, this project seems almost dead... so there is probably two options:

1. you acknowledge the weakness of the basic authentication logic given by `go-http-auth` and add the recommandation from @nakacya 
2. simply drop it from the project and leave only the recommandation from @nakacya

**Comment by Jiab77** [comment]
@ishiDACo, I just did some tests with the latest version (directly cloned the repo) and the issue still exists... I think you can simply drop it. On our side we've decided to not rely on `vulsrepo` to manage the authentication. Many thanks for your time on this issue.

**Comment by ishiDACo** [comment]
I've made a pull request for a document update.

https://github.com/vulsdoc/vuls/pull/117

**Comment by Jiab77** [comment]
@ishiDACo Thanks a lot for the documentation update.

**Comment by Jiab77** [comment]
@ishiDACo I guess this issue can be closed now?
