### ISSUE TITLE
Generate report result to document vulsrepo

### ISSUE THREAD

**Issue by neofallxyz** [ishiDACo/vulsrepo#173]
Hello, 
can vulsrepo generate report result for document report (like .pdf or csv)?

**Comment by ishiDACo** [comment]
The pdf and csv output is not available as a standard renderer for pivottable.js, which vulsrepo uses.
However, for TSV output it seems to be possible.

https://github.com/nicolaskruchten/pivottable/wiki/Optional-Extra-Renderers
https://pivottable.js.org/examples/mps_export.html

**Comment by ishiDACo** [comment]
Now, I am implementing TSV download feature.
You will be able to download and save the TSV. 
You can open the file with an editor that can handle it (e.g. LibreOffice Calc 6).

**Comment by ishiDACo** [comment]
PDF file saving may also be possible. I'll try to see if I can.
https://github.com/nicolaskruchten/pivottable/issues/58#issuecomment-180555606
https://github.com/MrRio/jsPDF

**Comment by ishiDACo** [comment]
Dynamic generation of PDF is difficult, such as layout and font support.
Instead, try to prepare pages for printing.

**Comment by ishiDACo** [comment]
Printable pages can now be displayed in a separate window. This allows you to print just the tables and graphs on the printer or save them as PDF file (depending on your browser's printing capabilities).
