### ISSUE TITLE
Parse report from URL

### ISSUE THREAD

**Issue by Jiab77** [ishiDACo/vulsrepo#189]
Hello @ishiDACo, it's not a real issue but more a feature request. I'm wondering if that's possible to parse and display report specified in URL like https://hostname:5111/2020-12-11T18:00:00+01:00/scanned-host.json ?

The idea behind that is to use reports pushed to another `HTTP` endpoint and draw a web interface with direct links pointing to the report generated by your project.

See here for reference: https://vuls.io/docs/en/usage-settings.html#http-section

> I'm actually writing the documentation. I'll update this issue to include pull request link.

**Comment by Jiab77** [comment]
Pull request about the required config: https://github.com/vulsdoc/vuls/pull/135

**Comment by Jiab77** [comment]
Pull request about the usage: https://github.com/vulsdoc/vuls/pull/136

**Comment by Jiab77** [comment]
@ishiDACo, thanks a lot for the label 👍🏼

**Comment by ishiDACo** [comment]
>  https://hostname:5111/2020-12-11T18:00:00+01:00/scanned-host.json

Since it is only a client-side modification, I would like to pass the parameter as a get query string as shown below.

https://hostname:5111?time=2020-12-11T18:00:00+01:00&server=scanned-host.json

**Comment by Jiab77** [comment]
@ishiDACo, oh right! I agree with you, really good idea 👍🏼

**Comment by ishiDACo** [comment]
For more information, please see https://github.com/ishiDACo/vulsrepo/releases/tag/v0.4.0

**Comment by Jiab77** [comment]
@ishiDACo, thank you so much for your work, I'll test it this week and let you know 😉
