### ISSUE TITLE
Corresponds to the -diff option

### ISSUE THREAD

**Issue by kazuminn** [ishiDACo/vulsrepo#212]
https://github.com/future-architect/vuls/pull/1157

The diff specification has changed with this commit.

https://github.com/future-architect/vuls/blob/master/models/vulninfos.go#L181

DiffStatus determines whether the difference is plus or minus in _diff.json.

Please correspond properly.

**Comment by ishiDACo** [comment]
It looks like the following.

![image](https://user-images.githubusercontent.com/2542762/107731040-46e5e600-6d38-11eb-8245-0556528c13a4.png)

**Comment by kazuminn** [comment]
@ishiDACo 

I think it looks good.
I hope it can be displayed separately for plus and minus

Thanks

**Comment by ishiDACo** [comment]
You can select `+` or `-` in the `Diff` filter to show only `+` or `-`.

![image](https://user-images.githubusercontent.com/2542762/107734069-e2c72000-6d3f-11eb-8fbd-189a82295cf1.png)

![image](https://user-images.githubusercontent.com/2542762/107734112-fb373a80-6d3f-11eb-8ccf-a44b94eeb6c2.png)

**Comment by kazuminn** [comment]
@ishiDACo 

Great!!!
