### ISSUE TITLE
Documentation please

### ISSUE THREAD

**Issue by jirib** [ishiDACo/vulsrepo#56]
For a newbie like me it's totally unknown how to interpret all those reports in vulsrepo web UI. Is there any tutorial or could you make one and document it please?

Thank you very much.

**Comment by ishiDACo** [comment]
Right now, no tutorial document.
Official document is [https://vuls.io/docs/en/vulsrepo.html](https://vuls.io/docs/en/vulsrepo.html) on older version.

I would like to revise the document when I have some free time.

**Comment by ishiDACo** [comment]
@jirib The document has been updated.
https://vuls.io/docs/en/vulsrepo.html
